<?php

namespace Database\Seeders;


use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = [
            [
                'id' => 1,
                'category_id' => 1,
                'name' => 'Cooler Master MM711',
                'price' => 270,
                'company' => 'Cooler Master',
                'discount' => 0,
                'amount' => 20,
                'click' => fake()->numberBetween(110,250),
                'description' => 'this is supposed to be a description.',
                'image' => 'MM711.png',
                'color' => 'Black',
                'product_code' => 'dsfg34g35hg535h',
                'purchased_price' => 250,
                'visibility' => 1,
            ],
            [
                'id' => 2,
                'category_id' => 1,
                'name' => 'Cooler Master MM710',
                'price' => 230,
                'company' => 'COOLER MASTER',
                'discount' => 0,
                'amount' => 20,
                'click' => fake()->numberBetween(110,250),
                'description' => 'this is supposed to be a description.',
                'image' => 'MM710.png',
                'color' => 'Black',
                'product_code' => 'dsfg34g45hg535h',
                'purchased_price' => 200,
                'visibility' => 1,
            ],
            [
                'id' => 3,
                'category_id' => 1,
                'name' => 'MOUSE LOGITECH G402 HYPERION FURY',
                'price' => 150,
                'company' => 'LOGITECH',
                'discount' => 0,
                'amount' => 20,
                'click' => fake()->numberBetween(110,250),
                'description' => 'this is supposed to be a description.',
                'image' => 'LOGITECH_G402.png',
                'color' => 'Black',
                'product_code' => 'dsfg34g55hg535h',
                'purchased_price' => 125,
                'visibility' => 1,
            ],
            [
                'id' => 4,
                'category_id' => 1,
                'name' => 'MOUSE LOGITECH G403 HERO',
                'price' => 200,
                'company' => 'LOGITECH',
                'discount' => 0,
                'amount' => 20,
                'click' => fake()->numberBetween(110,250),
                'description' => 'this is supposed to be a description.',
                'image' => 'LOGITECH_G403.png',
                'color' => 'Black',
                'product_code' => 'dsfg22g55hg535h',
                'purchased_price' => 150,
                'visibility' => 1,
            ],
            [
                'id' => 5,
                'category_id' => 1,
                'name' => 'MOUSE RAZER DEATHADDER V2 WIRED',
                'price' => 250,
                'company' => 'RAZER',
                'discount' => 2,
                'amount' => 20,
                'click' => fake()->numberBetween(110,250),
                'description' => 'this is supposed to be a description.',
                'image' => 'DEATHADDER_V2.png',
                'color' => 'Black',
                'product_code' => 'dgfg22g55hg535h',
                'purchased_price' => 200,
                'visibility' => 1,
            ],
            [
                'id' => 6,
                'category_id' => 1,
                'name' => 'MOUSE RAZER BASILISK V2 ERGONOMIC',
                'price' => 200,
                'company' => 'RAZER',
                'discount' => 5,
                'amount' => 20,
                'click' => fake()->numberBetween(110,250),
                'description' => 'this is supposed to be a description.',
                'image' => 'BASILISK_V2_ERGONOMIC.png',
                'color' => 'Black',
                'product_code' => 'd2hg22g55hg535h',
                'purchased_price' => 120,
                'visibility' => 1,
            ],
            ////////////////////////KeyBoards////////////////////////////////////////////////////////////////////////////////////////////////////
            [
                'id' => 7,
                'category_id' => 2,
                'name' => 'KEYBOARD RAZER BLACKWIDOV3 TENKEYLESS CHROMA RGB',
                'price' => 350,
                'company' => 'RAZER',
                'discount' => 0,
                'amount' => 22,
                'click' => fake()->numberBetween(110,250),
                'description' => 'this is supposed to be a description.',
                'image' => 'BLACKWIDOV3-TENKEYLESS-CHROMA.png',
                'color' => 'Black',
                'product_code' => 'd2hg22g55hg535h',
                'purchased_price' => 270,
                'visibility' => 1,
            ],
            [
                'id' => 8,
                'category_id' => 2,
                'name' => 'KEYBOARD RAZER CYNOSA LITE ESSENTIAL CHROMA RGB',
                'price' => 350,
                'company' => 'RAZER',
                'discount' => 0,
                'amount' => 22,
                'click' => fake()->numberBetween(110,250),
                'description' => 'this is supposed to be a description.',
                'image' => 'CYNOSA-LITE ESSENTIAL.png',
                'color' => 'Black',
                'product_code' => 'd2hg22g5ttt535h',
                'purchased_price' => 270,
                'visibility' => 1,
            ],
            [
                'id' => 9,
                'category_id' => 2,
                'name' => 'KEYBOARD COOLERMASTER CK550 V2 MECHANICAL RED',
                'price' => 200,
                'company' => 'COOLER MASTER',
                'discount' => 0,
                'amount' => 22,
                'click' => fake()->numberBetween(110,250),
                'description' => 'this is supposed to be a description.',
                'image' => 'CK550-V2.png',
                'color' => 'Black',
                'product_code' => 'd2hgyyg55hg535h',
                'purchased_price' => 180,
                'visibility' => 1,
            ],
            [
                'id' => 10,
                'category_id' => 2,
                'name' => 'KEYBOARD COOLERMASTER CK550 V2 MECHANICAL RED',
                'price' => 180,
                'company' => 'COOLER MASTER',
                'discount' => 0,
                'amount' => 22,
                'click' => fake()->numberBetween(110,250),
                'description' => 'this is supposed to be a description.',
                'image' => 'MK750.png',
                'color' => 'Black',
                'product_code' => 'd2hgssg55hg535h',
                'purchased_price' => 200,
                'visibility' => 1,
            ],
            [
                'id' => 11,
                'category_id' => 2,
                'name' => 'KEYBOARD LOGITECH G413 SE MECHANICAL GAMING US INTL',
                'price' => 300,
                'company' => 'LOGITECH',
                'discount' => 0,
                'amount' => 22,
                'click' => fake()->numberBetween(110,250),
                'description' => 'this is supposed to be a description.',
                'image' => 'G413-SE.png',
                'color' => 'Black',
                'product_code' => 'd2hgffg55hg535h',
                'purchased_price' => 250,
                'visibility' => 1,
            ],
            [
                'id' => 12,
                'category_id' => 2,
                'name' => 'KEYBOARD CORSAIR K60 RGB PRO MECHANICAL ENGLISH',
                'price' => 380,
                'company' => 'CORSAIR',
                'discount' => 0,
                'amount' => 22,
                'click' => fake()->numberBetween(110,250),
                'description' => 'this is supposed to be a description.',
                'image' => 'CORSAIR-K6.png',
                'color' => 'Black',
                'product_code' => 'd2hggtg55hg535h',
                'purchased_price' => 330,
                'visibility' => 1,
            ],
            ////////////////////CPU///////////////////////////////////////////////////////////////////////////////////////////////////////////
            [
                'id' => 13,
                'category_id' => 3,
                'name' => 'CPU AMD RYZEN 7 5800X BOX',
                'price' => 1200,
                'company' => 'AMD',
                'discount' => 0,
                'amount' => 22,
                'click' => fake()->numberBetween(110,250),
                'description' => 'this is supposed to be a description.',
                'image' => 'RYZEN-7-5800X.png',
                'color' => 'Black',
                'product_code' => 'd2hg4rg55hg535h',
                'purchased_price' => 950,
                'visibility' => 1,
            ],
            [
                'id' => 14,
                'category_id' => 3,
                'name' => 'CPU AMD RYZEN 5 5600 BOX',
                'price' => 770,
                'company' => 'AMD',
                'discount' => 0,
                'amount' => 22,
                'click' => fake()->numberBetween(110,250),
                'description' => 'this is supposed to be a description.',
                'image' => 'RYZEN-5-5600.png',
                'color' => 'Black',
                'product_code' => 'd2hgjjg55hg535h',
                'purchased_price' => 680,
                'visibility' => 1,
            ],
            [
                'id' => 15,
                'category_id' => 3,
                'name' => 'CPU AMD RYZEN 9 7950X BOX',
                'price' => 3200,
                'company' => 'AMD',
                'discount' => 0,
                'amount' => 22,
                'click' => fake()->numberBetween(110,250),
                'description' => 'this is supposed to be a description.',
                'image' => 'RYZEN-9-7950X.png',
                'color' => 'Black',
                'product_code' => 'd2hg4ji55hg535h',
                'purchased_price' => 2900,
                'visibility' => 1,
            ],
            [
                'id' => 16,
                'category_id' => 3,
                'name' => 'CPU INTEL I5 10600K BOX',
                'price' => 699,
                'company' => 'INTEL',
                'discount' => 0,
                'amount' => 22,
                'click' => fake()->numberBetween(110,250),
                'description' => 'this is supposed to be a description.',
                'image' => 'INTEL-I5-10600K.png',
                'color' => 'Black',
                'product_code' => 'd2hg4ji55hkk35h',
                'purchased_price' => 610,
                'visibility' => 1,
            ],
            [
                'id' => 17,
                'category_id' => 3,
                'name' => 'CPU INTEL I7 13700K BOX',
                'price' => 1700,
                'company' => 'INTEL',
                'discount' => 0,
                'amount' => 22,
                'click' => fake()->numberBetween(110,250),
                'description' => 'this is supposed to be a description.',
                'image' => 'INTEL-I7-13700K.png',
                'color' => 'Black',
                'product_code' => 'd2hg4ji55hgl35h',
                'purchased_price' => 1500,
                'visibility' => 1,
            ],
            [
                'id' => 18,
                'category_id' => 3,
                'name' => 'CPU INTEL I5 13600KF BOX',
                'price' => 1200,
                'company' => 'INTEL',
                'discount' => 0,
                'amount' => 22,
                'click' => fake()->numberBetween(110,250),
                'description' => 'this is supposed to be a description.',
                'image' => 'INTEL-I5-13600KF.png',
                'color' => 'Black',
                'product_code' => 'd2hg4ji55hpp35h',
                'purchased_price' => 1050,
                'visibility' => 1,
            ],
            ////////////////GPU////////////////////////////////////////////////////////////////////////////////////////////////////////////
            [
                'id' => 19,
                'category_id' => 4,
                'name' => 'GPU ASUS DUAL GTX1660S-O6G-EVO',
                'price' => 999,
                'company' => 'ASUS',
                'discount' => 0,
                'amount' => 22,
                'click' => fake()->numberBetween(110,250),
                'description' => 'this is supposed to be a description.',
                'image' => 'GT-1660S-O6G-EVO.png',
                'color' => 'Black',
                'product_code' => 'd2hghji55hpp35h',
                'purchased_price' => 890,
                'visibility' => 1,
            ],
            [
                'id' => 20,
                'category_id' => 4,
                'name' => 'ASUS GeForce ROG STRIX RTX 3070 O8G WHITE V2',
                'price' => 2300,
                'company' => 'ASUS',
                'discount' => 0,
                'amount' => 22,
                'click' => fake()->numberBetween(110,250),
                'description' => 'this is supposed to be a description.',
                'image' => 'GT-1660S-O6G-EVO.png',
                'color' => 'White',
                'product_code' => 'd2hghji55hee35h',
                'purchased_price' => 1900,
                'visibility' => 1,
            ],
            [
                'id' => 21,
                'category_id' => 4,
                'name' => 'GPU GALAX GTX1660TI-6GB-1-CLICK-OC',
                'price' => 999,
                'company' => 'GALAX',
                'discount' => 0,
                'amount' => 22,
                'click' => fake()->numberBetween(110,250),
                'description' => 'this is supposed to be a description.',
                'image' => 'GTX1660TI-6GB-1-CLICK-OC.png',
                'color' => 'Black',
                'product_code' => 'd2hghji55huu35h',
                'purchased_price' => 890,
                'visibility' => 1,
            ],
            [
                'id' => 22,
                'category_id' => 4,
                'name' => 'GPU ASUS DUAL RTX3050-O8G-GAMING',
                'price' => 1200,
                'company' => 'ASUS',
                'discount' => 0,
                'amount' => 22,
                'click' => fake()->numberBetween(110,250),
                'description' => 'this is supposed to be a description.',
                'image' => 'GPU-AS-D3050-O8.png',
                'color' => 'Black',
                'product_code' => 'd2httji55huu35h',
                'purchased_price' => 990,
                'visibility' => 1,
            ],
            [
                'id' => 23,
                'category_id' => 4,
                'name' => 'ASUS Dual GeForce RTX 3060 White OC Edition 8GB GDDR6',
                'price' => 1600,
                'company' => 'ASUS',
                'discount' => 0,
                'amount' => 22,
                'click' => fake()->numberBetween(110,250),
                'description' => 'this is supposed to be a description.',
                'image' => 'GeForce-RTX-3060-White.png',
                'color' => 'White',
                'product_code' => 'd2httj125huu35h',
                'purchased_price' => 1490,
                'visibility' => 1,
            ],
            [
                'id' => 24,
                'category_id' => 4,
                'name' => 'GPU ASUS TUF RTX3060-O12G-V2-GAMING',
                'price' => 1600,
                'company' => 'ASUS',
                'discount' => 0,
                'amount' => 22,
                'click' => fake()->numberBetween(110,250),
                'description' => 'this is supposed to be a description.',
                'image' => 'GPU-AS-TUF3060V.png',
                'color' => 'Black',
                'product_code' => 'd2httj125hu335h',
                'purchased_price' => 1490,
                'visibility' => 1,
            ],
            //////////////Headphones///////////////////////////////////////////////////////////////////////////////////////////
            [
                'id' => 25,
                'category_id' => 5,
                'name' => 'HEADSET SOUND BlasterX H6 GAMING 7.1 USB',
                'price' => 220,
                'company' => 'CREATIVE',
                'discount' => 0,
                'amount' => 22,
                'click' =>fake()->numberBetween(110,250),
                'description' => 'this is supposed to be a description.',
                'image' => 'BlasterX-H6.png',
                'color' => 'Black',
                'product_code' => 'd2htyp125hu335h',
                'purchased_price' => 200,
                'visibility' => 1,
            ],
            [
            'id' => 26,
            'category_id' => 5,
            'name' => 'HEADSET LOGITECH G432 7.1',
            'price' => 180,
            'company' => 'LOGITECH',
            'discount' => 0,
            'amount' => 22,
            'click' => fake()->numberBetween(110,250),
            'description' => 'this is supposed to be a description.',
            'image' => 'LOGITECH-G432.png',
            'color' => 'Black',
            'product_code' => 'd2rryp125hu335h',
            'purchased_price' => 165,
            'visibility' => 1,
        ],
        [
            'id' => 27,
            'category_id' => 5,
            'name' => 'HEADSET RAZER KRAKEN X MERCURY WHITE 7.1',
            'price' => 199,
            'company' => 'RAZER',
            'discount' => 0,
            'amount' => 22,
            'click' => fake()->numberBetween(110,250),
            'description' => 'this is supposed to be a description.',
            'image' => 'HS-KRAKENX-MERC.png',
            'color' => 'White',
            'product_code' => 'd2rry4445hu335h',
            'purchased_price' => 175,
            'visibility' => 1,
        ],
        [
            'id' => 28,
            'category_id' => 5,
            'name' => 'HEADSET CORSAIR VIRTUOSO RGB WIRELESS WHITE',
            'price' => 600,
            'company' => 'CORSAIR',
            'discount' => 0,
            'amount' => 22,
            'click' => fake()->numberBetween(110,250),
            'description' => 'this is supposed to be a description.',
            'image' => 'HS-VIRTUOSO-RGB.png',
            'color' => 'White',
            'product_code' => 'd2rry2225hu335h',
            'purchased_price' => 550,
            'visibility' => 1,
        ],
        [
            'id' => 29,
            'category_id' => 5,
            'name' => 'HEADSET HYPERX CLOUD FLIGHT WIFI GAMING BLACK',
            'price' => 600,
            'company' => 'HYPERX',
            'discount' => 0,
            'amount' => 22,
            'click' =>fake()->numberBetween(110,250),
            'description' => 'this is supposed to be a description.',
            'image' => 'HS-FLIGHT-WIFI.png',
            'color' => 'Black',
            'product_code' => 'd2rry22rh5hu445h',
            'purchased_price' => 540,
            'visibility' => 1,
        ],
        [
            'id' => 30,
            'category_id' => 5,
            'name' => 'HEADSET ASUS ROG THETA ELECTRET STEREO',
            'price' => 350,
            'company' => 'HYPERX',
            'discount' => 0,
            'amount' => 22,
            'click' => fake()->numberBetween(110,250),
            'description' => 'this is supposed to be a description.',
            'image' => 'HS-ROG-THETA-EL.png',
            'color' => 'Black',
            'product_code' => 'd2rry22rh5ht465h',
            'purchased_price' => 290,
            'visibility' => 1,
        ],
        //////////////Monitors////////////////////////////////////////////////////////////////////////////
        [
            'id' => 31,
            'category_id' => 6,
            'name' => 'MONITOR AOC 27G2U/BK 27″ IPS 144HZ',
            'price' => 950,
            'company' => 'AOC',
            'discount' => 0,
            'amount' => 22,
            'click' => fake()->numberBetween(110,250),
            'description' => 'this is supposed to be a description.',
            'image' => 'MONITOR-AOC-27G2U.png',
            'color' => 'Black',
            'product_code' => 'd21rss2rh5hu445h',
            'purchased_price' => 800,
            'visibility' => 1,
        ],
        [
            'id' => 32,
            'category_id' => 6,
            'name' => 'MONITOR AOC C27G1 27” CURVED VA 144HZ',
            'price' => 850,
            'company' => 'AOC',
            'discount' => 0,
            'amount' => 22,
            'click' => fake()->numberBetween(110,250),
            'description' => 'this is supposed to be a description.',
            'image' => 'c27g1.png',
            'color' => 'Black',
            'product_code' => 'd21rss23gyhu445h',
            'purchased_price' => 700,
            'visibility' => 1,
        ],
        [
            'id' => 33,
            'category_id' => 6,
            'name' => 'MONITOR ASUS TUF VG259QM 24.5″ IPS 280HZ',
            'price' => 1500,
            'company' => 'ASUS',
            'discount' => 0,
            'amount' => 22,
            'click' => fake()->numberBetween(110,250),
            'description' => 'this is supposed to be a description.',
            'image' => 'ASUS-TUF-VG259QM.png',
            'color' => 'Black',
            'product_code' => 'd21r4sfdd5hu445h',
            'purchased_price' => 1410,
            'visibility' => 1,
        ],
        [
            'id' => 34,
            'category_id' => 6,
            'name' => 'MONITOR ASUS ROG STRIX XG43UQ 43” 4K UHD VA 144HZ',
            'price' => 5200,
            'company' => 'ASUS',
            'discount' => 0,
            'amount' => 22,
            'click' => fake()->numberBetween(110,250),
            'description' => 'this is supposed to be a description.',
            'image' => 'MT-AS-XG43UQ.png',
            'color' => 'Black',
            'product_code' => 'd21r4sdst5hu445h',
            'purchased_price' => 4900,
            'visibility' => 1,
        ],
        [
            'id' => 35,
            'category_id' => 6,
            'name' => 'MONITOR ASUS ROG SWIFT PG259QNR 24.5” IPS FHD 360HZ',
            'price' => 1450,
            'company' => 'ASUS',
            'discount' => 0,
            'amount' => 22,
            'click' => fake()->numberBetween(110,250),
            'description' => 'this is supposed to be a description.',
            'image' => 'MT-AS-PG259QNR.png',
            'color' => 'Black',
            'product_code' => 'd21r4sdst5hu4z5h',
            'purchased_price' => 1300,
            'visibility' => 1,
        ],
        [
            'id' => 36,
            'category_id' => 6,
            'name' => 'MONITOR GIGABYTE G27QC 27″ CURVED VA 165HZ',
            'price' => 1200,
            'company' => 'GIGABYTE',
            'discount' => 0,
            'amount' => 22,
            'click' => fake()->numberBetween(110,250),
            'description' => 'this is supposed to be a description.',
            'image' => 'MT-GB-G27QC.png',
            'color' => 'Black',
            'product_code' => 'd21r4sdst5hu4aah',
            'purchased_price' => 990,
            'visibility' => 1,
        ],


        ];


        foreach ($products as $product)
        {
           $newProduct= Product::create($product);

          

        }
    }
}
